### ISSUE TITLE
yarn 下载报错

### ISSUE THREAD

**Issue by marshall-li** [wangeditor-team/wangEditor-plugin-ctrl-enter#2]
我在使用yarn下载时终端报错了 插件未下载成功
Error: EISDIR: illegal operation on a directory, read
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:173:14
    at FSReqCallback.wrapper [as oncomplete] (fs.js:562:5)
![image](https://user-images.githubusercontent.com/81742076/230526951-0bb2b9a7-5a14-4e5e-ac82-334d68009d85.png)

ps: yarn版本 1.22.17 是版本的问题吗

**Comment by marshall-li** [comment]
使用npm i @wangeditor/plugin-ctrl-enter 下载成功了 不知道yarn出什么问题了
